### ISSUE TITLE
scroll lateral

### ISSUE THREAD

**Issue by AndresAlzateHoyos** [Gisel23/mercadoLiebre#2]
Scroll lateral a la derecha por tener en 133% el width de .logo-contenedor2 en css: 87. Cuando disminuye, se hace más pequeño el banner, esto se puede solucionar quitando la clase .logo-contenedor de la section y poniéndola directamente en la img del banner.

**Comment by Gisel23** [comment]
La imagen del banner se encuentra en sus dimensiones correctas aún cuando pasamos de distintas dimensiones de pantalla, se probó la propuesta comentada en el issue pero no quedaba centrada, con lo cual no se procedió a la modificación
